package problems;

public class Problem002 {

	/**
	 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	 * 			1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	 */
	public static void main(String[] args) {
		// Fibonacci sequence starting values
		int a = 1;
		int b = 2;
		
		int maxValue = 4000000;
		int nextValue = 0;
		int sumOfEvens = 0;
		
		while (nextValue < maxValue){
			if (b % 2 == 0)
				sumOfEvens += b;

			nextValue = a + b;
			a = b;
			b = nextValue;
		}
		System.out.println("The sum of all even numbers, under 4 million, in the Fibonacci sequence is " + sumOfEvens);
	}
}
